name: Actions workflow

on: 
  # filtrando para ser acionado somente na master, tb funciona com o pull-request
  push:
    #temos branches e branches-ignore, que s처 podem ser usadas separadamente
    branches:
      - master
      # filtra pelo inicio do nome da branch, ex feature/123, bate com qualquer um exceto /
      - 'feature/*'
      # bate com todos, inclusive /, ex feature/123/a
      - 'feature/**'
      # o ! ignora a feature, ent찾o essa n찾o seria calculada
      - '!feature/featc'
    tags:
    # temos tags e tags-ignore, funcionam como branches
      - v1.*
    paths:
    # compila quando fizermos push com js, qualquer outra coisa n찾o funciona
      - '**.js'
  # repository_dispatch:
  # schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  # push:
  # pull_request:
  #  types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payloas
        # este env veio do build pelo postman
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: List Files Again
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"