name: matrix

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        exclude:
          - os: macos-latest
            node-version: 6
          - os: windows-latest
            node-version: 8
        include:
          - os: ubuntu-latest
            node-version: 8
            is-ubuntu-8: "true"
      # limita a quantidade de jobs em paralelo
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS-UBUNTU-8: ${{ matrix.is-ubuntu-8 }}
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node-version
        run: | 
          node -v
          echo $IS-UBUNTU-8